<h1>Página de Listar</h1>

<hr>
<table class="container table table-strped table-hover">
    <thead class="table-dark">
        <tr>
            <td>ID</td>
            <td>NOME</td>
            <td>CIDADE</td>
            <td>MATRICULA</td>
            <td>Ações</td>
        </tr>
    </thead>
    <tbody>
        <?php
            foreach($dados as $row){
                $id = $row['idAluno'];
                echo " <tr>
                    <td>{$row['idAluno']}</td>
                    <td>{$row['nome']}</td>
                    <td>{$row['cidade']}</td>
                    <td>{$row['matricula']}</td>
                    <td>
                        <a href='/update?id={$id}' class='btn btn-outline-warning'>Editar</a>
                        <button  onclick='getIdAluno($id)' data-bs-toggle='modal' data-bs-target='#exampleModal' class='btn btn-outline-danger'>Excluir</button>
                    </td>
                </tr>";
            }
        ?>
    </tbody>
    
</table>

<script>
    function getIdAluno(id) {
        deleteAluno.value = id;
    }

    function confirmDelete() {
        id = deleteAluno.value
        location.href = '/delete?id='+id;
        
    }
    
</script>

<!-- Modal de exclusão do aluno -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Excluir aluno</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Tem certeza que vai excluir esse aluno?
        <input type="hidden" id="deleteAluno">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary"  onclick='confirmDelete()'>Confirm</button>
      </div>
    </div>
  </div>
</div>