<h1>New</h1>

<form action="#" method="post">
    <input required value="<?php echo $_POST['nome'] ?? '' ?>" type="text" name="nome" placeholder="Nome">
    <input required value="<?php echo $_POST['cidade'] ?? '' ?>" type="text" name="cidade" placeholder="cidade">
    <input required value="<?php echo $_POST['matricula'] ?? '' ?>" type="text" name="matricula" placeholder="matricula">
    <button type="submit" name="cadastrar">clica</button>
</form>