<h1>Página de Editar</h1>

<form action="#" method="post">
    <input type="text" name="nome" placeholder="Nome" value="<?php echo $_POST['nome'] ?? $dados["nome"]?>">
    <input type="text" name="cidade" placeholder="cidade" value="<?php echo $_POST['cidade'] ?? $dados["cidade"]?>">
    <input type="text" name="matricula" placeholder="matricula" value="<?php echo $_POST['matricula'] ?? $dados["matricula"]?>">
    <button type="submit" >clica</button>
</form>