<h1>Página de Editar</h1>

<form action="#" method="post">
    <input type="text" name="nome" placeholder="Nome" value="<?php echo $aluno["nome"]?>">
    <input type="text" name="cidade" placeholder="cidade" value="<?php echo $aluno["cidade"]?>">
    <input type="text" name="matricula" placeholder="matricula" value="<?php echo $aluno["matricula"]?>">
    <button type="submit" >clica</button>
</form>